const seallist = [
  {
    path: "sealimgs/US_Department_of_Health_and_Human_Services_seal.svg",
    title: "Department of Health and Human Services",
    id: "dhs",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_District_of_Columbia.svg",
    title: "District of Columbia",
    id: "dc",
    tags: ["State"],
  },
  {
    path: "sealimgs/Civil_Aerospace_Medical_Logo_4inch.jpg",
    title: "Civil Aerospace Medical Institute",
    id: "CAMI",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_President_of_the_United_States.svg",
    title: "President of The United States",
    id: "potus",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/United_States_Department_of_Transportation_seal.svg",
    title: "Department of Transportation",
    id: "dot",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Idaho.svg",
    title: "Idaho",
    id: "ID",
    tags: ["State"],
  },
  {
    path: "sealimgs/State_seal_of_Iowa.svg",
    title: "Iowa",
    id: "IA",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Utah.svg",
    title: "Utah",
    id: "UT",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_State_of_Nebraska.svg",
    title: "Nebraska",
    id: "NE",
    tags: ["State"],
  },
  {
    path: "sealimgs/State_Seal_of_South_Dakota.svg",
    title: "South Dakota",
    id: "SD",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Guam.svg",
    title: "Guam",
    id: "guam",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Maryland_reverse.svg",
    title: "Maryland (Reverse)",
    id: "MDr",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_North_Carolina_1971.svg",
    title: "North Carolina (1971)",
    id: "NC1971",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Seal_of_New_York.svg",
    title: "New York",
    id: "NY",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Louisiana_1879.png",
    title: "Louisana (Historical)",
    id: "LAh",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Great_Seal_of_the_Philippine_Islands.svg",
    title: "Philippine Islands",
    id: "phi",
    tags: ["State"],
  },
  {
    path: "sealimgs/CIASTA_logo.svg",
    title:
      "Cooperative Institute for Atmospheric Sciences and Terrestrial Applications",
    id: "ciasta",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Massachusetts.svg",
    title: "Massachusetts",
    id: "MA",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Arkansas.svg",
    title: "Arkansas",
    id: "AR",
    tags: ["State"],
  },
  {
    path: "sealimgs/Great_Seal_of_North_Dakota.svg",
    title: "North Dakota",
    id: "ND",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Mississippi_1818.png",
    title: "Mississippi (Historical)",
    id: "MIh",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Seal_of_West_Virginia.svg",
    title: "West Virginia",
    id: "WV",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Education.svg",
    title: "Department of Education",
    id: "doEd",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Ohio_1967.svg",
    title: "Ohio (1967)",
    id: "OH1967",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_the_Treasury.svg",
    title: "Department of the Treasury",
    id: "treasury",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Mississippi_1879.svg",
    title: "Mississippi (1879)",
    id: "MS1879",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Arizona_state_seal.svg",
    title: "Arizona",
    id: "AZ",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Rhode_Island.svg",
    title: "Rhode Island",
    id: "RI",
    tags: ["State"],
  },
  {
    path: "sealimgs/US_Department_of_Agriculture_seal.svg",
    title: "Department of Agriculture",
    id: "doa",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Choctaw_seal.svg",
    title: "Choctaw Nation",
    id: "choctaw",
    tags: ["Tribal"],
  },
  {
    path: "sealimgs/Seal_of_the_U.S._Department_of_Veterans_Affairs.svg",
    title: "Department of Veterans Affairs",
    id: "vetA",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Commerce.svg",
    title: "Department of Commerce",
    id: "doc",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_Panama_Canal_Zone.svg",
    title: "Panama Canal Zone",
    id: "pcz",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Maryland_obverse.svg",
    title: "Maryland",
    id: "MDo",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_North_Carolina.svg",
    title: "North Carolina",
    id: "NC",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Colorado.svg",
    title: "Colorado",
    id: "CO",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_State_of_Hawaii.svg",
    title: "Hawaii",
    id: "HI",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_New_Hampshire.svg",
    title: "New Hampshire",
    id: "NH",
    tags: ["State"],
  },
  {
    path: "sealimgs/Great_Seal_of_the_United_States_reverse.svg",
    title: "Great Seal (Reverse)",
    id: "GSr",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Defense.svg",
    title: "Department of Defense",
    id: "dod",
    tags: ["Federal", "Military"],
  },
  {
    path: "sealimgs/Seal_of_Louisiana_1902.svg",
    title: "Louisana",
    id: "LA",
    tags: ["State"],
  },
  {
    path: "sealimgs/State_Seal_of_Nevada.svg",
    title: "Nevada",
    id: "NV",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_Northern_Mariana_Islands.svg",
    title: "Northern Mariana Islands",
    id: "nmi",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Texas.svg",
    title: "Texas",
    id: "TX",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_American_Samoa.svg",
    title: "American Samoa",
    id: "as",
    tags: [],
  },
  {
    path: "sealimgs/State_Seal_of_Vermont.svg",
    title: "Vermont",
    id: "VT",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Virginia.svg",
    title: "Virginia",
    id: "VA",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Maine.svg",
    title: "Maine",
    id: "ME",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Homeland_Security.svg",
    title: "Department of Homeland Security",
    id: "dhs2",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Justice.svg",
    title: "Department of Justice",
    id: "doj",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_Territory_of_Hawaii.svg",
    title: "Hawaii (Territory)",
    id: "HIt",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Seal_of_the_State_of_Alaska.svg",
    title: "Alaska",
    id: "AK",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_the_Interior.svg",
    title: "Department of the Interior",
    id: "doi",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Osage_Nation.svg",
    title: "Osage Nation",
    id: "osage",
    tags: ["Tribal"],
  },
  {
    path: "sealimgs/Seal_of_South_Carolina.svg",
    title: "South Carolina",
    id: "SC",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Housing_and_Urban_Development.svg",
    title: "Department of Housing and Urban Development",
    id: "HUD",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Georgia.svg",
    title: "Georgia",
    id: "GA",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Michigan.svg",
    title: "Michigan",
    id: "MI",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Missouri.svg",
    title: "Missouri",
    id: "MO",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Virgin_Islands.svg",
    title: "Virgin Islands",
    id: "virginislands",
    tags: [],
  },
  {
    path: "sealimgs/Seal_of_Kentucky.svg",
    title: "Kentucky",
    id: "KY",
    tags: ["State"],
  },
  {
    path: "sealimgs/Wyoming-StateSeal.svg",
    title: "Wyoming",
    id: "WY",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Alabama_1817.svg",
    title: "Alabama 1817",
    id: "AL",
    tags: ["State, Historical"],
  },
  {
    path: "sealimgs/Seal_of_the_Commonwealth_of_Puerto_Rico.svg",
    title: "Puerto Rico",
    id: "PR",
    tags: [],
  },
  {
    path: "sealimgs/Seal_of_New_Jersey.svg",
    title: "New Jersey",
    id: "NJ",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_State_of_Indiana.svg",
    title: "Indiana",
    id: "IN",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Energy.svg",
    title: "Department of Energy",
    id: "doe",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Reverse_of_the_Seal_of_Texas.svg",
    title: "Texas (Reverse)",
    id: "TXr",
    tags: ["State"],
  },
  {
    path: "sealimgs/US_101st_Airborne_Division_patch.svg",
    title: "101st Airborne Division",
    id: "101a",
    tags: ["Military"],
  },
  {
    path: "sealimgs/Territorial_Seal_of_Utah_BHoU-p460.png",
    title: "Utah (Territory)",
    id: "utt",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Seal_of_Connecticut.svg",
    title: "Connecticut",
    id: "CT",
    tags: ["State"],
  },
  {
    path: "sealimgs/Great_seal_of_the_cherokee_nation.svg",
    title: "Cherokee Nation",
    id: "cherokee",
    tags: ["Tribal"],
  },
  {
    path: "sealimgs/Seal_of_Alabama_1868.svg",
    title: "Alabama",
    id: "AL1868",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_New_Mexico.svg",
    title: "New Mexico",
    id: "NM",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Florida.svg",
    title: "Florida",
    id: "FL",
    tags: ["State"],
  },
  {
    path: "sealimgs/State_Seal_of_Minnesota.svg",
    title: "Minnesota",
    id: "MN",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Louisiana.svg",
    title: "Louisiana",
    id: "LA2",
    tags: ["State"],
  },
  {
    path: "sealimgs/Haudenosaunee_seal.png",
    title: "Six Nations",
    id: "6N",
    tags: ["Tribal"],
  },
  {
    path: "sealimgs/Seal_of_Mississippi.svg",
    title: "Mississippi",
    id: "MI3",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Montana.svg",
    title: "Montana",
    id: "MT",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Wisconsin.svg",
    title: "Wisconsin",
    id: "WI",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Illinois.svg",
    title: "Illinois",
    id: "IL",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Alabama.svg",
    title: "Alabama",
    id: "AL2",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Pennsylvania.svg",
    title: "Pennsylvania",
    id: "PA",
    tags: ["State"],
  },
  {
    path: "sealimgs/U.S._Department_of_State_official_seal.svg",
    title: "Department of State",
    id: "DOS",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Colorado_old.png",
    title: "Colorado (Historical)",
    id: "COh",
    tags: ["State", "Historical"],
  },
  {
    path: "sealimgs/Seal_of_Delaware.svg",
    title: "Delaware",
    id: "DE",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Department_of_Labor.svg",
    title: "Department of Labor",
    id: "DOL",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Tennessee.svg",
    title: "Tennessee",
    id: "TN",
    tags: ["State"],
  },
  {
    path: "sealimgs/Great_Seal_of_the_United_States_(obverse).svg.webp",
    title: "Great Seal",
    id: "GSo",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_Kansas.svg",
    title: "Kansas",
    id: "KS",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Oregon.svg",
    title: "Oregon",
    id: "OR",
    tags: ["State"],
  },
  {
    path: "sealimgs/Hopi_seal.svg",
    title: "Hopi Tribe",
    id: "hopi",
    tags: ["Tribal"],
  },
  {
    path: "sealimgs/Great_Seal_of_the_Navajo_Nation.svg",
    title: "Navajo Nation",
    id: "navajo",
    tags: ["Tribal"],
  },
  {
    path: "sealimgs/Seal_of_California.svg",
    title: "California",
    id: "CA",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Ohio.svg",
    title: "Ohio",
    id: "OH",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_Oklahoma.svg",
    title: "Oklahoma",
    id: "OK",
    tags: ["State"],
  },
  {
    path: "sealimgs/Seal_of_the_Office_of_the_Director_of_National_Intelligence.svg",
    title: "Office of the Director of National Intelligence",
    id: "ODNI",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_Central_Intelligence_Agency.svg",
    title: "Central Intelligence Agency",
    id: "CIA",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/US-NationalGeospatialIntelligenceAgency-2008Seal.svg",
    title: "National Geospatial-Intelligence Agency",
    id: "NGIA",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_Coast_Guard_Intelligence.svg",
    title: "Coast Guard Intelligence",
    id: "CGI",
    tags: ["Military"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Army_Military_Intelligence_Corps.svg",
    title: "Military Intelligence Corps",
    id: "MIC",
    tags: ["Military"],
  },
  {
    path: "sealimgs/Final_ONI_seal.png",
    title: "Office of Naval Intelligence",
    id: "ONI",
    tags: ["Military"],
  },
  {
    path: "sealimgs/Seal_of_the_U.S._National_Security_Agency.svg",
    title: "National Security Agency",
    id: "NSA",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_United_States_Intelligence_Community.svg",
    title: "United States Intelligence Community",
    id: "USIC",
    tags: ["Federal"],
  },
  {
    path: "sealimgs/Seal_of_the_U.S._Defense_Intelligence_Agency.svg",
    title: "Defense Intelligence Agency",
    id: "DIA",
    tags: ["Military"],
  },
  {
    path: "sealimgs/Bureau_of_Intelligence_and_Research_Seal.svg",
    title: "Bureau of Intelligence and Research",
    id: "INR",
    tags: ["Federal"],
  },
];
export default seallist;
